/*!
Project Euler
http://projecteuler.net/


Problem 2: Even Fibonacci numbers
"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."

Solution by: A.Woroniuk 

Completed? Yes

 *
 */

var maxnumber = 4000000;
var eventotal = 0;
var first = 0;
var second = 1;
var nextnumber = 0;


while (nextnumber < maxnumber) {
	if (nextnumber % 2 == 0) {
 		eventotal = eventotal + nextnumber;
 	}

 	nextnumber = first + second;
 	first = second;
 	second = nextnumber;

}
document.write(eventotal)